/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import java.util.ArrayList;

/**
 *
 * @author nanil
 */
public class Ventas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventas.class.getName());
    private java.util.List<proyectofinal.Producto> productosVenta = new java.util.ArrayList<>();
    private double subtotal = 0.0;


    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        CodigoProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaVenta = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        Cancelar1 = new javax.swing.JButton();
        generarFactura = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Subtotal = new javax.swing.JLabel();
        IVA = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();

        jButton5.setText("Agregar a la Venta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Ventas | FideCompro");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Codigo de Producto");

        agregar.setText("Agregar a la Venta");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        AreaVenta.setColumns(20);
        AreaVenta.setRows(5);
        jScrollPane1.setViewportView(AreaVenta);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Esta Venta");

        eliminar.setText("Eliminar de la Venta");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        Cancelar1.setText("Salir");
        Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar1ActionPerformed(evt);
            }
        });

        generarFactura.setBackground(new java.awt.Color(51, 153, 255));
        generarFactura.setForeground(new java.awt.Color(255, 255, 255));
        generarFactura.setText("Generar Factura");
        generarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarFacturaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Subtotal");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("I.V.A 13%");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total");

        Subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Subtotal.setText("0");

        IVA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IVA.setText("0");

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total.setText("0");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Cedula");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                                        .addGap(63, 63, 63))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(agregar)
                                                .addGap(18, 18, 18)
                                                .addComponent(eliminar))
                                            .addComponent(CodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cancelar1)
                                .addGap(18, 18, 18)
                                .addComponent(generarFactura)
                                .addGap(17, 17, 17))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Subtotal)
                            .addComponent(IVA)
                            .addComponent(total))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(CodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(eliminar))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar1)
                    .addComponent(generarFactura))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Subtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IVA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total)))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        String codigo = CodigoProducto.getText().trim();
        if (codigo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un código de producto.");
            return;
        }

        java.util.List<proyectofinal.Producto> todosLosProductos = proyectofinal.Producto.LeerProductos();
        proyectofinal.Producto productoEncontrado = null;

        for (proyectofinal.Producto p : todosLosProductos) {
            if (p.getCodigo().equalsIgnoreCase(codigo)) {
                productoEncontrado = p;
                break;
            }
        }

        if (productoEncontrado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            return;
        }

        
        productosVenta.add(productoEncontrado);
        subtotal += productoEncontrado.getPrecio();

        
        AreaVenta.append(productoEncontrado.getNombre() + " - " + String.format("₡%.2f", productoEncontrado.getPrecio()) + "\n");

        
        double iva = subtotal * 0.13;
        double totalFinal = subtotal + iva;

        
        Subtotal.setText(String.format("₡%.2f", subtotal));
        IVA.setText(String.format("₡%.2f", iva));
        total.setText(String.format("₡%.2f", totalFinal));

        
        CodigoProducto.setText("");

    }//GEN-LAST:event_agregarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        if (productosVenta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay productos en la venta.");
            return;
        }

        proyectofinal.Producto eliminado = productosVenta.remove(productosVenta.size() - 1);
        subtotal -= eliminado.getPrecio();

        
        AreaVenta.setText("");
        for (proyectofinal.Producto p : productosVenta) {
            AreaVenta.append(p.getNombre() + " - " + String.format("₡%.2f", p.getPrecio()) + "\n");
        }

        double iva = subtotal * 0.13;
        double totalFinal = subtotal + iva;

        Subtotal.setText(String.format("₡%.2f", subtotal));
        IVA.setText(String.format("₡%.2f", iva));
        total.setText(String.format("₡%.2f", totalFinal));

    }//GEN-LAST:event_eliminarActionPerformed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_Cancelar1ActionPerformed

    private void generarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarFacturaActionPerformed
        // TODO add your handling code here:
        if (productosVenta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay productos en la venta.");
            return;
        }

        String cedulaTexto = cedula.getText().trim();
        if (cedulaTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar la cédula del cliente.");
            return;
        }

        ArrayList<proyectofinal.Cliente> clientes = proyectofinal.Cliente.LeerClientes();
        proyectofinal.Cliente clienteEncontrado = null;
        for (proyectofinal.Cliente c : clientes) {
            if (c.getCedula().equalsIgnoreCase(cedulaTexto)) {
                clienteEncontrado = c;
                break;
            }
        }

        if (clienteEncontrado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente no registrado. Regístrelo primero.");
            return;
        }

        
        StringBuilder factura = new StringBuilder();
        factura.append("----- FideCompro -----\n");
        factura.append("Factura generada el ").append(java.time.LocalDateTime.now()).append("\n\n");
        factura.append("Cliente: ").append(clienteEncontrado.getNombre()).append(" ").append(clienteEncontrado.getApellidos()).append("\n");
        factura.append("Cédula: ").append(clienteEncontrado.getCedula()).append("\n\n");
        factura.append("Productos:\n");

        for (proyectofinal.Producto p : productosVenta) {
            factura.append(" - ").append(p.getNombre()).append(": ₡").append(String.format("%.2f", p.getPrecio())).append("\n");
        }

        factura.append("\nSubtotal: ").append(Subtotal.getText());
        factura.append("\nIVA (13%): ").append(IVA.getText());
        factura.append("\nTotal: ").append(total.getText());
        factura.append("\n---------------------------\n");

        //Guardar en txt
        try {
            String nombreArchivo = "Factura_" + java.time.LocalDateTime.now()
                    .toString().replace(":", "-").replace(".", "-") + ".txt";
            java.io.FileWriter writer = new java.io.FileWriter(nombreArchivo);
            writer.write(factura.toString());
            writer.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Factura generada y guardada como:\n" + nombreArchivo);
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la factura: " + e.getMessage());
            return;
        }

        
        productosVenta.clear();
        subtotal = 0.0;
        Subtotal.setText("₡0.00");
        IVA.setText("₡0.00");
        total.setText("₡0.00");
        AreaVenta.setText("");
        CodigoProducto.setText("");
        cedula.setText("");

        
        
        
        
    }//GEN-LAST:event_generarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaVenta;
    private javax.swing.JButton Cancelar1;
    private javax.swing.JTextField CodigoProducto;
    private javax.swing.JLabel IVA;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cedula;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton generarFactura;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
