/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

/**
 *
 * @author nanil
 */
public class VentanaInventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInventario.class.getName());

    /**
     * Creates new form VentanaInventario
     */
    public VentanaInventario() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AreaInventario.setEditable(false);
        AreaInventario.setFont(new java.awt.Font("monospaced", java.awt.Font.PLAIN, 12));
        resultadoConsulta.setEditable(false);
        resultadoConsulta.setFont(new java.awt.Font("monospaced", java.awt.Font.PLAIN, 12));
        cargarInventario();
    }
    
    private void cargarInventario() {
        AreaInventario.setText("Cargando...\n");
        new javax.swing.SwingWorker<java.util.List<Cliente.net.ClientApi.ProductoDet>, Void>() {
            String error=null;
            @Override protected java.util.List<Cliente.net.ClientApi.ProductoDet> doInBackground() {
                try { return new Cliente.net.ClientApi().productoListar(); }
                catch (Exception ex){ error=ex.getMessage(); return java.util.List.of(); }
            }
            @Override protected void done() {
                try {
                    java.util.List<Cliente.net.ClientApi.ProductoDet> lista = get();
                    if (error != null) { AreaInventario.setText("Error: " + error); return; }
                    StringBuilder sb = new StringBuilder();
                    for (Cliente.net.ClientApi.ProductoDet p : lista) {
                        sb.append(String.format("%s | %-18s | %5d | %10.2f%n",
                                p.codigo, p.nombre, p.stock, p.precio));
                    }
                    AreaInventario.setText(sb.toString());
                } catch (Exception ignored) {
                    AreaInventario.setText("Error inesperado.");
                }
            }

        }.execute();
    }
    private Integer parseCantidad(String s){
        try { int v = Integer.parseInt(s.trim()); return v; } catch(Exception e){ return null; }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaInventario = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        Cancelar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CodigoProductoGranular = new javax.swing.JTextField();
        agregarInventarioGranular = new javax.swing.JButton();
        cantidadProductoGranular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EliminarInventarioGranular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CodigoProductoborrar = new javax.swing.JTextField();
        EliminacionTotal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        consulta = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();
        tipoConsulta = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadoConsulta = new javax.swing.JTextArea();
        btnMostrarTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Administrar Invenario | FideCompro");

        AreaInventario.setColumns(20);
        AreaInventario.setRows(5);
        jScrollPane1.setViewportView(AreaInventario);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Inventario");

        Cancelar1.setText("Salir");
        Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ajustes de stock");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Codigo de Producto");

        CodigoProductoGranular.setText("PRD-");

        agregarInventarioGranular.setText("Agregar al inventario");
        agregarInventarioGranular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarInventarioGranularActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Cantidad");

        EliminarInventarioGranular.setText("Eliminar cantidad");
        EliminarInventarioGranular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarInventarioGranularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(agregarInventarioGranular)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarInventarioGranular))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(CodigoProductoGranular, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(cantidadProductoGranular, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(CodigoProductoGranular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cantidadProductoGranular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarInventarioGranular)
                    .addComponent(EliminarInventarioGranular))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Eliminar articulos de la base de datos");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Codigo de Producto");

        CodigoProductoborrar.setText("PRD-");

        EliminacionTotal.setText("Eliminar del inventario");
        EliminacionTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminacionTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminacionTotal)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(CodigoProductoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(144, 144, 144))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(CodigoProductoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminacionTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        tipoConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo de articulo", "Nombre de articulo" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Consultar por");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Consultar existencia");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(consultar)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(consultar)
                .addGap(47, 47, 47))
        );

        labelResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelResultado.setText("Resultados");

        resultadoConsulta.setColumns(20);
        resultadoConsulta.setRows(5);
        jScrollPane2.setViewportView(resultadoConsulta);

        btnMostrarTodo.setText("Actualizar");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarTodo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelResultado)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)))
                                .addGap(205, 205, 205)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarTodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancelar1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarInventarioGranularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarInventarioGranularActionPerformed
        // TODO add your handling code here:
        String cod = CodigoProductoGranular.getText().trim().toUpperCase();
        Integer cant = parseCantidad(cantidadProductoGranular.getText());
        if (!cod.matches("PRD-\\d{3}") || cant==null || cant<=0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Código PRD-XXX y cantidad > 0");
            return;
        }
        bloquear(true);
        new javax.swing.SwingWorker<Boolean,Void>(){
            String err=null;
            @Override protected Boolean doInBackground(){
                try { return new Cliente.net.ClientApi().productoAjustar(cod, cant); }
                catch(Exception ex){ err=ex.getMessage(); return false; }
            }
            @Override protected void done(){
                bloquear(false);
                try{
                    if(get()){ javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Stock sumado"); cargarInventario(); }
                    else javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Error: "+err);
                }catch(Exception e){ javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Error inesperado");}
            }
        }.execute();
    }//GEN-LAST:event_agregarInventarioGranularActionPerformed

    private void EliminarInventarioGranularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarInventarioGranularActionPerformed
        // TODO add your handling code here:
        String cod = CodigoProductoGranular.getText().trim().toUpperCase();
        Integer cant = parseCantidad(cantidadProductoGranular.getText());
        if (!cod.matches("PRD-\\d{3}") || cant==null || cant<=0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Código PRD-XXX y cantidad > 0");
            return;
        }
        bloquear(true);
        new javax.swing.SwingWorker<Boolean,Void>(){
            String err=null;
            @Override protected Boolean doInBackground(){
                try { return new Cliente.net.ClientApi().productoAjustar(cod, -cant); }
                catch(IllegalArgumentException iae){ err="No puede quedar negativo"; return false; }
                catch(Exception ex){ err=ex.getMessage(); return false; }
            }
            @Override protected void done(){
                bloquear(false);
                try{
                    if(get()){ javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Stock restado"); cargarInventario(); }
                    else javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Error: "+err);
                }catch(Exception e){ javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Error inesperado");}
            }
        }.execute();
    

    }//GEN-LAST:event_EliminarInventarioGranularActionPerformed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_Cancelar1ActionPerformed

    private void EliminacionTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminacionTotalActionPerformed
        // TODO add your handling code here:
        String cod = CodigoProductoborrar.getText().trim().toUpperCase();
        if (!cod.matches("PRD-\\d{3}")){ javax.swing.JOptionPane.showMessageDialog(this,"Código PRD-XXX"); return; }
        int ok = javax.swing.JOptionPane.showConfirmDialog(this,"¿Eliminar definitivamente "+cod+"?","Confirmar",javax.swing.JOptionPane.YES_NO_OPTION);
        if (ok!=javax.swing.JOptionPane.YES_OPTION) return;

        bloquear(true);
        new javax.swing.SwingWorker<Boolean,Void>(){
            String err=null;
            @Override protected Boolean doInBackground(){
                try { return new Cliente.net.ClientApi().productoEliminar(cod); }
                catch(IllegalStateException ise){ err=ise.getMessage(); return false; }
                catch(Exception ex){ err=ex.getMessage(); return false; }
            }
            @Override protected void done(){
                bloquear(false);
                try{
                    if(get()){ javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Producto eliminado"); cargarInventario(); }
                    else {
                        String msg = "Error: "+err;
                        if (err!=null && err.contains("facturas")) msg = "No se puede eliminar: el producto ya tiene facturas.";
                        javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this, msg);
                    }
                }catch(Exception e){ javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Error inesperado");}
            }
        }.execute();
    }//GEN-LAST:event_EliminacionTotalActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        String criterio = consulta.getText().trim();
        if (criterio.isBlank()){ javax.swing.JOptionPane.showMessageDialog(this,"Ingrese criterio"); return; }
        boolean porCodigo = tipoConsulta.getSelectedIndex()==0;

        bloquear(true);
        new javax.swing.SwingWorker<String,Void>(){
            String err=null;
            @Override protected String doInBackground(){
                try {
                    Cliente.net.ClientApi api = new Cliente.net.ClientApi();
                    if (porCodigo){
                        var d = api.productoGet(criterio.toUpperCase());
                        return String.format("%s | %s | %s | %d | %.2f",
                                d.codigo, d.nombre, d.descripcion, d.stock, d.precio);
                    } else {
                        var lista = api.productoBuscarNombre(criterio);
                        StringBuilder sb=new StringBuilder();
                        for (var p: lista)
                            sb.append(String.format("%s | %-18s | %5d | %10.2f%n", p.codigo,p.nombre,p.stock,p.precio));
                        if (lista.isEmpty()) sb.append("Sin coincidencias.");
                        return sb.toString();
                    }
                } catch(Exception ex){ err=ex.getMessage(); return null; }
            }
            @Override protected void done(){
                bloquear(false);
                try{
                    String s = get();
                    if (s==null){ javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Error: "+err); return; }
                    resultadoConsulta.setText(s); // ← ahora va aquí
                }catch(Exception e){ javax.swing.JOptionPane.showMessageDialog(VentanaInventario.this,"Error inesperado");}
            }
        }.execute();
    }//GEN-LAST:event_consultarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:
        cargarInventario();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInventario().setVisible(true));
    }
    private void bloquear(boolean b){
        agregarInventarioGranular.setEnabled(!b);
        EliminarInventarioGranular.setEnabled(!b);
        EliminacionTotal.setEnabled(!b);
        consultar.setEnabled(!b);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaInventario;
    private javax.swing.JButton Cancelar1;
    private javax.swing.JTextField CodigoProductoGranular;
    private javax.swing.JTextField CodigoProductoborrar;
    private javax.swing.JButton EliminacionTotal;
    private javax.swing.JButton EliminarInventarioGranular;
    private javax.swing.JButton agregarInventarioGranular;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JTextField cantidadProductoGranular;
    private javax.swing.JTextField consulta;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextArea resultadoConsulta;
    private javax.swing.JComboBox<String> tipoConsulta;
    // End of variables declaration//GEN-END:variables
}
