/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;
//En Db.ensureSchema() crea facturas y detalle_factura (te lo pasé antes).

//Crea Servidor/servicio/FacturaServicio.java (tal como te lo compartí antes; maneja transacción, descuenta stock y devuelve el texto en Base64).

//En ServidorMain.procesar añade FACTURA_CREAR (el bloque que te di antes).

/**
 *
 * @author nanil
 */
public class Ventas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventas.class.getName());


    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        
    }
    private static class Item {
        String codigo, nombre;
        double precio;
        int cantidad;
        Item(String c, String n, double p, int q){ codigo=c; nombre=n; precio=p; cantidad=q; }
    }
    private final java.util.List<Item> carrito = new java.util.ArrayList<>();
    private double subtotalN = 0.0;

    private void refrescarVista() {
        AreaVenta.setText("");
        for (Item it : carrito) {
            AreaVenta.append(it.codigo + " - " + it.nombre + " x" + it.cantidad +
                             " = ₡" + String.format("%.2f", it.precio * it.cantidad) + "\n");
        }
        subtotalN = carrito.stream().mapToDouble(i -> i.precio * i.cantidad).sum();
        double iva = subtotalN * 0.13;
        double tot = subtotalN + iva;
        Subtotal.setText(String.format("₡%.2f", subtotalN));
        IVA.setText(String.format("₡%.2f", iva));
        total.setText(String.format("₡%.2f", tot));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        CodigoProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaVenta = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        Cancelar1 = new javax.swing.JButton();
        generarFactura = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Subtotal = new javax.swing.JLabel();
        IVA = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        verInventario = new javax.swing.JButton();

        jButton5.setText("Agregar a la Venta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Ventas | FideCompro");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Codigo de Producto");

        agregar.setText("Agregar a la Venta");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        CodigoProducto.setText("PRD-");

        AreaVenta.setColumns(20);
        AreaVenta.setRows(5);
        jScrollPane1.setViewportView(AreaVenta);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Esta Venta");

        eliminar.setText("Eliminar de la Venta");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        Cancelar1.setText("Salir");
        Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar1ActionPerformed(evt);
            }
        });

        generarFactura.setBackground(new java.awt.Color(51, 153, 255));
        generarFactura.setForeground(new java.awt.Color(255, 255, 255));
        generarFactura.setText("Generar Factura");
        generarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarFacturaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Subtotal");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("I.V.A 13%");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total");

        Subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Subtotal.setText("0");

        IVA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IVA.setText("0");

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total.setText("0");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Cedula");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Cantidad");

        verInventario.setBackground(new java.awt.Color(51, 153, 255));
        verInventario.setForeground(new java.awt.Color(255, 255, 255));
        verInventario.setText("Ver Inventario");
        verInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                                        .addGap(63, 63, 63))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(agregar)
                                                .addGap(18, 18, 18)
                                                .addComponent(eliminar))
                                            .addComponent(jLabel10)
                                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(CodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(verInventario)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Cancelar1)
                                        .addGap(18, 18, 18)
                                        .addComponent(generarFactura)))
                                .addGap(17, 17, 17))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Subtotal)
                            .addComponent(IVA)
                            .addComponent(total))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(verInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(CodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(eliminar))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar1)
                    .addComponent(generarFactura))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Subtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IVA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total)))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        String codigo = CodigoProducto.getText().trim().toUpperCase();
        if (codigo.isEmpty()) { javax.swing.JOptionPane.showMessageDialog(this, "Ingrese código"); return; }

        String cantStr = cantidad.getText().trim();
        int cant;
        try {
            cant = Integer.parseInt(cantStr);
            if (cant <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cantidad inválida");
            return;
        }
        final int yaEnCarrito = carrito.stream()
                .filter(it -> it.codigo.equalsIgnoreCase(codigo))
                .mapToInt(it -> it.cantidad)
                .sum();

        agregar.setEnabled(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        new javax.swing.SwingWorker<Item, Void>() {
            String error = null;
            @Override protected Item doInBackground() {
                try {
                    var api = new Cliente.net.ClientApi();
                    var det = api.productoGet(codigo); // tiene: codigo, nombre, precio, stock

                    if (cant + yaEnCarrito > det.stock) {
                        int disponibleParaAgregar = Math.max(0, det.stock - yaEnCarrito);
                        error = "Stock insuficiente. Disponible para agregar ahora: " + disponibleParaAgregar;
                        return null;
                    }
                    return new Item(det.codigo, det.nombre, det.precio, cant);
                } catch (Exception ex) {
                    error = "Servidor: " + ex.getMessage();
                    return null;
                }
            }
            @Override protected void done() {
                agregar.setEnabled(true);
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                try {
                    Item it = get();
                    if (it == null) { javax.swing.JOptionPane.showMessageDialog(Ventas.this, error); return; }

                    
                    boolean merged = false;
                    for (Item x : carrito) {
                        if (x.codigo.equalsIgnoreCase(it.codigo)) {
                            x.cantidad += it.cantidad;   
                            merged = true;
                            break;
                        }
                    }
                    if (!merged) carrito.add(it);

                    refrescarVista();
                    CodigoProducto.setText("");
                    cantidad.setText("");
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(Ventas.this, "Error inesperado");
                }
            }
        }.execute();

    }//GEN-LAST:event_agregarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        String codigo = CodigoProducto.getText().trim().toUpperCase();
        if (codigo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el código a eliminar");
            return;
        }
        String cantStr = cantidad.getText().trim();
        int cant;
        try {
            cant = Integer.parseInt(cantStr);
            if (cant <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cantidad a eliminar inválida");
            return;
        }

        
        int totalEnCarrito = 0;
        for (Item it : carrito) {
            if (it.codigo.equalsIgnoreCase(codigo)) totalEnCarrito += it.cantidad;
        }
        if (totalEnCarrito == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ese producto no está en la venta.");
            return;
        }
        if (cant > totalEnCarrito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Solo hay " + totalEnCarrito + " unidades de " + codigo + " en la venta.");
            return;
        }

       
        int aEliminar = cant;
        for (int i = carrito.size() - 1; i >= 0 && aEliminar > 0; i--) {
            Item it = carrito.get(i);
            if (!it.codigo.equalsIgnoreCase(codigo)) continue;

            if (it.cantidad > aEliminar) {
                it.cantidad -= aEliminar;
                aEliminar = 0;
            } else {
                aEliminar -= it.cantidad;
                carrito.remove(i);
            }
        }

        refrescarVista();
        CodigoProducto.setText("PRD-");
        cantidad.setText("");

    }//GEN-LAST:event_eliminarActionPerformed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_Cancelar1ActionPerformed

    private void generarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarFacturaActionPerformed
        // TODO add your handling code here:
        if (carrito.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay productos en la venta.");
            return;
        }

        String clienteCed = cedula.getText().trim();
        if (!clienteCed.matches("\\d{9,10}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cédula de cliente inválida");
            return;
        }

        String usuarioCed = Cliente.Sesion.getUsuarioCedula();
        if (usuarioCed == null || !usuarioCed.matches("\\d{9,10}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay usuario en sesión. Inicie sesión nuevamente.");
            return;
        }

        generarFactura.setEnabled(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        new javax.swing.SwingWorker<Boolean, Void>() {
            String error = null, base64 = null; int facturaId = -1;

            @Override protected Boolean doInBackground() {
                try {
                    var api = new Cliente.net.ClientApi();
                    java.util.List<String> codCant = new java.util.ArrayList<>();
                    for (Item it : carrito) codCant.add(it.codigo + "^" + it.cantidad);
                    var r = api.facturaCrear(clienteCed, usuarioCed, codCant);
                    if (!r.ok) { error = r.mensaje; return false; }
                    base64 = r.textoBase64; facturaId = r.id;
                    return true;
                } catch (Exception ex) { error = "Servidor: " + ex.getMessage(); return false; }
            }

            @Override protected void done() {
                generarFactura.setEnabled(true);
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                try {
                    if (!get()) { javax.swing.JOptionPane.showMessageDialog(Ventas.this, error); return; }

                    byte[] bytes = java.util.Base64.getDecoder().decode(base64);
                    String texto = new String(bytes, java.nio.charset.StandardCharsets.UTF_8);
                    String nombreArchivo = "Factura_" + java.time.LocalDateTime.now()
                            .toString().replace(":", "-").replace(".", "-") + "_ID" + facturaId + ".txt";
                    try (java.io.FileWriter w = new java.io.FileWriter(nombreArchivo)) { w.write(texto); }
                    javax.swing.JOptionPane.showMessageDialog(Ventas.this, "Factura generada:\n" + nombreArchivo);

                    carrito.clear(); refrescarVista();
                    CodigoProducto.setText(""); cantidad.setText(""); cedula.setText("");

                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(Ventas.this, "Error inesperado al guardar la factura.");
                }
            }
        }.execute();
        
    }//GEN-LAST:event_generarFacturaActionPerformed

    private void verInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInventarioActionPerformed
        // TODO add your handling code here:
        VentanaMiniInventario v = new VentanaMiniInventario();
        v.setLocationRelativeTo(this); // centra respecto a Ventas
        v.setVisible(true);
    }//GEN-LAST:event_verInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaVenta;
    private javax.swing.JButton Cancelar1;
    private javax.swing.JTextField CodigoProducto;
    private javax.swing.JLabel IVA;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField cedula;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton generarFactura;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel total;
    private javax.swing.JButton verInventario;
    // End of variables declaration//GEN-END:variables
}
