/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

/**
 *
 * @author nanil
 */
public class VentanaClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaClientes.class.getName());

    /**
     * Creates new form VentanaClientes
     */
    public VentanaClientes() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AreaInventario.setEditable(false);
        resultadoConsulta.setEditable(false);
        setEmpresaVisible(false);
        setCamposEdicionEnabled(false);
        ajustarCamposConsulta();
        tipoConsulta.addActionListener(e -> ajustarCamposConsulta());
        cargarClientes();

    }
    private void setEmpresaVisible(boolean show){
        labelEmpresa.setVisible(show);
        empresafield.setVisible(show);
    }
    private void setCamposEdicionEnabled(boolean enabled){
        nombre.setEditable(enabled);
        apellidos.setEditable(enabled);
        email.setEditable(enabled);
        empresafield.setEditable(enabled && labelEmpresa.isVisible());
    }
    private void ajustarCamposConsulta(){
        boolean porCedula = "Cedula".equals(String.valueOf(tipoConsulta.getSelectedItem()));
        nombreConsulta.setVisible(!porCedula);
        ApellidosConsulta.setVisible(!porCedula);
        apellidosConsulta.setVisible(!porCedula);
        CedulaNombreConsulta.setToolTipText(porCedula ? "Cédula" : "Nombre");
    }
    private void cargarClientes() {
        AreaInventario.setText("Cargando...\n");
        new javax.swing.SwingWorker<java.util.List<Cliente.net.ClientApi.ClienteDet>, Void>() {
            String error = null;
            @Override protected java.util.List<Cliente.net.ClientApi.ClienteDet> doInBackground() {
                try { return new Cliente.net.ClientApi().clienteListar(); }
                catch (Exception ex) { error = ex.getMessage(); return java.util.List.of(); }
            }
            @Override protected void done() {
                try {
                    var lista = get();
                    if (error != null) { AreaInventario.setText("Error: " + error); return; }
                    StringBuilder sb = new StringBuilder();
                    for (var c : lista) {
                        sb.append(String.format("%s | %s %s | %s%s%n",
                            c.cedula, c.nombre, c.apellidos, c.correo,
                            c.esJuridica() ? " | " + (c.empresa == null ? "" : c.empresa) : ""));
                    }
                    AreaInventario.setText(sb.toString());
                } catch (Exception e) { AreaInventario.setText("Error inesperado."); }
            }
        }.execute();
    }
    private String formatearCliente(Cliente.net.ClientApi.ClienteDet c){
        return String.format(
            "%s | %s %s | %s%s",
            c.cedula, c.nombre, c.apellidos, c.correo,
            c.esJuridica() ? " | " + (c.empresa == null ? "" : c.empresa) : ""
        );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaInventario = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        Cancelar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CodigoProductoGranular = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        guardarCambios = new javax.swing.JButton();
        apellidos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        buscarCedulaEditar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        labelEmpresa = new javax.swing.JLabel();
        empresafield = new javax.swing.JTextField();
        CedulaEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CedulaBorrar = new javax.swing.JTextField();
        EliminacionTotal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        consultar = new javax.swing.JButton();
        tipoConsulta = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CedulaNombreConsulta = new javax.swing.JTextField();
        ApellidosConsulta = new javax.swing.JLabel();
        apellidosConsulta = new javax.swing.JTextField();
        nombreConsulta = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadoConsulta = new javax.swing.JTextArea();
        btnMostrarTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Administrar Clientes | FideCompro");

        AreaInventario.setColumns(20);
        AreaInventario.setRows(5);
        jScrollPane1.setViewportView(AreaInventario);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Lista de Clientes");

        Cancelar1.setText("Salir");
        Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Editar Cliente");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Cedula");

        CodigoProductoGranular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoProductoGranularActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nombre");

        guardarCambios.setText("Guardar cambios");
        guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Apellidos");

        buscarCedulaEditar.setText("Buscar");
        buscarCedulaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCedulaEditarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Email");

        labelEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEmpresa.setText("Empresa");

        CedulaEditar.setText("Buscar");
        CedulaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(197, 197, 197))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(guardarCambios)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodigoProductoGranular, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buscarCedulaEditar)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addComponent(CedulaEditar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(apellidos)
                                .addContainerGap())))
                    .addComponent(email)
                    .addComponent(empresafield)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelEmpresa)
                        .addGap(208, 208, 208))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CodigoProductoGranular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CedulaEditar))
                    .addComponent(buscarCedulaEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empresafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(guardarCambios)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Eliminar cliente de la base de datos");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Cedula");

        EliminacionTotal.setText("Eliminar de base de datos");
        EliminacionTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminacionTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(CedulaBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(144, 144, 144))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(EliminacionTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(CedulaBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(EliminacionTotal)
                .addContainerGap())
        );

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        tipoConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Nombre" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Consultar por");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Consultar existencia");

        ApellidosConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ApellidosConsulta.setText("Apellidos");

        nombreConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreConsulta.setText("Nombre");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(consultar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreConsulta)
                            .addComponent(CedulaNombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ApellidosConsulta)
                                .addGap(118, 118, 118))
                            .addComponent(apellidosConsulta))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nombreConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CedulaNombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ApellidosConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidosConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(consultar)
                .addContainerGap())
        );

        labelResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelResultado.setText("Resultados");

        resultadoConsulta.setColumns(20);
        resultadoConsulta.setRows(5);
        jScrollPane2.setViewportView(resultadoConsulta);

        btnMostrarTodo.setText("Actualizar");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarTodo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelResultado)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)))
                                .addGap(205, 205, 205)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarTodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(Cancelar1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_Cancelar1ActionPerformed

    private void guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosActionPerformed
        // TODO add your handling code here:
        String ced = CodigoProductoGranular.getText().trim();
        if (!ced.matches("\\d{9,10}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cédula inválida (9-10 dígitos).");
            return;
        }

        String nom = nombre.getText().trim();
        String ape = apellidos.getText().trim();
        String cor = email.getText().trim();
        boolean esJuridica = labelEmpresa.isVisible(); 
        String emp = esJuridica ? empresafield.getText().trim() : null;

        if (nom.isBlank()) { javax.swing.JOptionPane.showMessageDialog(this, "Nombre es obligatorio."); return; }
        if (!esJuridica && ape.isBlank()) { javax.swing.JOptionPane.showMessageDialog(this, "Apellidos son obligatorios."); return; }
        if (esJuridica && (emp == null || emp.isBlank())) { javax.swing.JOptionPane.showMessageDialog(this, "Empresa es obligatoria para cédula jurídica."); return; }
        if (!cor.isBlank() && !cor.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Correo electrónico inválido.");
            return;
        }
        if (cor.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Correo es obligatorio.");
            return;
        }
        if (!cor.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Correo electrónico inválido.");
            return;
        }

        guardarCambios.setEnabled(false);

        new javax.swing.SwingWorker<Boolean, Void>() {
            String error = null;
            @Override protected Boolean doInBackground() {
                try {
                    var api = new Cliente.net.ClientApi();
                    return api.clienteActualizar(ced, nom, ape, cor, emp);
                } catch (IllegalArgumentException iae) {
                    error = iae.getMessage(); return false;
                } catch (Exception ex) {
                    error = ex.getMessage(); return false;
                }
            }
            @Override protected void done() {
                guardarCambios.setEnabled(true);
                try {
                    if (get()) {
                        javax.swing.JOptionPane.showMessageDialog(VentanaClientes.this, "Cambios guardados.");
                        
                        setCamposEdicionEnabled(false);
                        
                        cargarClientes();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(VentanaClientes.this, "No se pudo actualizar: " + error);
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(VentanaClientes.this, "Error inesperado.");
                }
            }
        }.execute();

    }//GEN-LAST:event_guardarCambiosActionPerformed

    private void EliminacionTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminacionTotalActionPerformed
        // TODO add your handling code here:
        final String ced = CedulaBorrar.getText().trim();
        if (!ced.matches("\\d{9,10}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cédula inválida (9-10 dígitos).");
            return;
        }

        int opt = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Eliminar cliente " + ced + "?\nEsta acción no se puede deshacer.",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        if (opt != javax.swing.JOptionPane.YES_OPTION) return;

        EliminacionTotal.setEnabled(false);

        new javax.swing.SwingWorker<Boolean, Void>() {
            String error = null;

            @Override protected Boolean doInBackground() {
                try {
                    return new Cliente.net.ClientApi().clienteEliminar(ced);
                } catch (IllegalStateException ise) {
                    error = ise.getMessage();
                    return false;
                } catch (Exception ex) {
                    error = ex.getMessage();
                    return false;
                }
            }

            @Override protected void done() {
                EliminacionTotal.setEnabled(true);
                try {
                    boolean ok = get();
                    if (ok) {
                        javax.swing.JOptionPane.showMessageDialog(VentanaClientes.this, "Cliente eliminado.");
                        CedulaBorrar.setText("");
                        if (ced.equals(CodigoProductoGranular.getText().trim())) {
                            nombre.setText("");
                            apellidos.setText("");
                            email.setText("");
                            empresafield.setText("");
                            setEmpresaVisible(false);
                            setCamposEdicionEnabled(false);
                        }
                        cargarClientes();
                    } else {
                        String msg;
                        if (error == null) {
                            msg = "No se pudo eliminar.";
                        } else if (error.contains("CLIENTE_TIENE_FACTURAS") || error.contains("FACTURAS")) {
                            msg = "No se puede eliminar: el cliente tiene facturas.";
                        } else if (error.contains("NO_ENCONTRADO")) {
                            msg = "No existe un cliente con esa cédula.";
                        } else {
                            msg = "Error: " + error;
                        }
                        javax.swing.JOptionPane.showMessageDialog(VentanaClientes.this, msg);
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(VentanaClientes.this, "Error inesperado.");
                }
            }
        }.execute();
    }//GEN-LAST:event_EliminacionTotalActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        boolean porCedula = "Cedula".equals(String.valueOf(tipoConsulta.getSelectedItem()));
        resultadoConsulta.setText("Buscando...\n");
        consultar.setEnabled(false);

        if (porCedula) {
            final String ced = CedulaNombreConsulta.getText().trim();
            if (!ced.matches("\\d{9,10}")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cédula inválida (9-10 dígitos).");
                resultadoConsulta.setText("");
                consultar.setEnabled(true);
                return;
            }
            new javax.swing.SwingWorker<Cliente.net.ClientApi.ClienteDet, Void>() {
                String error = null;
                @Override protected Cliente.net.ClientApi.ClienteDet doInBackground() {
                    try {
                        return new Cliente.net.ClientApi().clienteGet(ced);
                    } catch (Exception ex) {
                        error = ex.getMessage();
                        return null;
                    }
                }
                @Override protected void done() {
                    consultar.setEnabled(true);
                    try {
                        var det = get();
                        if (det == null) {
                            resultadoConsulta.setText(error != null ? "Error: " + error : "Sin resultados.");
                            return;
                        }
                        resultadoConsulta.setText(formatearCliente(det));
                    } catch (Exception e) {
                        resultadoConsulta.setText("Error inesperado.");
                    }
                }
            }.execute();

        } else {
            final String nom = CedulaNombreConsulta.getText() == null ? "" : CedulaNombreConsulta.getText().trim();
            final String ape = apellidosConsulta.getText() == null ? "" : apellidosConsulta.getText().trim();

            if (nom.isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El nombre es obligatorio para esta búsqueda.");
                resultadoConsulta.setText("");
                consultar.setEnabled(true);
                return;
            }

            new javax.swing.SwingWorker<java.util.List<Cliente.net.ClientApi.ClienteDet>, Void>() {
                String error = null;
                @Override protected java.util.List<Cliente.net.ClientApi.ClienteDet> doInBackground() {
                    try {
                        return new Cliente.net.ClientApi().clienteBuscarNombre(nom, ape);
                    } catch (Exception ex) {
                        error = ex.getMessage();
                        return java.util.List.of();
                    }
                }
                @Override protected void done() {
                    consultar.setEnabled(true);
                    try {
                        var lista = get();
                        if (error != null) {
                            resultadoConsulta.setText("Error: " + error);
                            return;
                        }
                        if (lista.isEmpty()) {
                            resultadoConsulta.setText("Sin resultados.");
                            return;
                        }
                        StringBuilder sb = new StringBuilder();
                        for (var c : lista) sb.append(formatearCliente(c)).append('\n');
                        resultadoConsulta.setText(sb.toString());
                    } catch (Exception e) {
                        resultadoConsulta.setText("Error inesperado.");
                    }
                }
            }.execute();
        }
    }//GEN-LAST:event_consultarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:
        cargarClientes();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void CodigoProductoGranularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoProductoGranularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoProductoGranularActionPerformed

    private void buscarCedulaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCedulaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCedulaEditarActionPerformed

    private void CedulaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaEditarActionPerformed
        // TODO add your handling code here:
        String ced = CodigoProductoGranular.getText().trim();
            if (!ced.matches("\\d{9,10}")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cédula inválida (9-10 dígitos).");
                return;
            }
            guardarCambios.setEnabled(false);

            new javax.swing.SwingWorker<Cliente.net.ClientApi.ClienteDet, Void>() {
                String error = null;
                @Override protected Cliente.net.ClientApi.ClienteDet doInBackground() {
                    try {
                        var api = new Cliente.net.ClientApi();
                        return api.clienteGet(ced); 
                    } catch (Exception ex) {
                        error = ex.getMessage();
                        return null;
                    }
                }
                @Override protected void done() {
                    guardarCambios.setEnabled(true);
                    try {
                        var det = get();
                        if (det == null) {
                            javax.swing.JOptionPane.showMessageDialog(
                                VentanaClientes.this,
                                error != null ? "Error: " + error : "Cliente no encontrado."
                            );
                            return;
                        }
                        nombre.setText(det.nombre);
                        apellidos.setText(det.apellidos);
                        email.setText(det.correo);
                        boolean esJuridica = "JURIDICA".equalsIgnoreCase(det.tipoCedula);
                        setEmpresaVisible(esJuridica);
                        empresafield.setText(esJuridica ? (det.empresa == null ? "" : det.empresa) : "");
                        setCamposEdicionEnabled(true);
                        if (!esJuridica) empresafield.setText("");  
                        email.requestFocusInWindow();
                    } catch (Exception e) {
                        javax.swing.JOptionPane.showMessageDialog(VentanaClientes.this, "Error inesperado.");
                    }
                }

            }.execute();
    }//GEN-LAST:event_CedulaEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidosConsulta;
    private javax.swing.JTextArea AreaInventario;
    private javax.swing.JButton Cancelar1;
    private javax.swing.JTextField CedulaBorrar;
    private javax.swing.JButton CedulaEditar;
    private javax.swing.JTextField CedulaNombreConsulta;
    private javax.swing.JTextField CodigoProductoGranular;
    private javax.swing.JButton EliminacionTotal;
    private javax.swing.JTextField apellidos;
    private javax.swing.JTextField apellidosConsulta;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton buscarCedulaEditar;
    private javax.swing.JButton consultar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField empresafield;
    private javax.swing.JButton guardarCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelEmpresa;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreConsulta;
    private javax.swing.JTextArea resultadoConsulta;
    private javax.swing.JComboBox<String> tipoConsulta;
    // End of variables declaration//GEN-END:variables
}
